### ISSUE TITLE
As a developer, I should be able to easily visualize any user context

### ISSUE THREAD

**Issue by GreenMobius** [amgassert/emberclear-democracy-prototype#36]

**Comment by GreenMobius** [comment]
Users can use the view-user-context command and it will pretty-print contexts. Discord roles can also be synced to contexts to easily visualize them.

**Comment by GreenMobius** [comment]
- roles aren't shown in the correct priority order
- consider adding colors to differentiate roles
- modify role such that it displays online users separately

**Comment by GreenMobius** [comment]
- still produces an error even though it succeeds

**Comment by CelticMajora** [comment]
- I'm not sure if there is a way to show roles separately using discord.js. I've been looking and it looks like you have to manually do it in the server's settings.
- I can get colors
- I can look into priority. There is a priority thing for roles, but I'm not sure it will impact the display order
- I'll look into the error upon success more

**Comment by CelticMajora** [comment]
Addressed by #55
